"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *
from ....primitives import *

class PacketPong(Packet):
	__slots__ = ( 'id', 'id' )
	
	id : int

	def __init__(self, 
		id:int | None = None,
		**kwargs
	):
		super().__init__(
			id=id
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		755 : 29,
		756 : 29,
		757 : 29,
		758 : 29,
		759 : 31,
		760 : 32,
		761 : 31
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		755 : [ ( 'id', Int ) ],
		756 : [ ( 'id', Int ) ],
		757 : [ ( 'id', Int ) ],
		758 : [ ( 'id', Int ) ],
		759 : [ ( 'id', Int ) ],
		760 : [ ( 'id', Int ) ],
		761 : [ ( 'id', Int ) ]
	}
