"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *
from ....primitives import *

class PacketOpenBook(Packet):
	__slots__ = ( 'id', 'hand' )
	
	hand : int

	def __init__(self, 
		hand:int | None = None,
		**kwargs
	):
		super().__init__(
			hand=hand
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		477 : 45,
		480 : 45,
		490 : 45,
		498 : 45,
		573 : 46,
		575 : 46,
		578 : 46,
		709 : 46,
		734 : 45,
		735 : 45,
		736 : 45,
		751 : 44,
		755 : 45,
		756 : 45,
		757 : 45,
		758 : 45,
		759 : 42,
		760 : 44,
		761 : 43
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		477 : [ ( 'hand', VarInt ) ],
		480 : [ ( 'hand', VarInt ) ],
		490 : [ ( 'hand', VarInt ) ],
		498 : [ ( 'hand', VarInt ) ],
		573 : [ ( 'hand', VarInt ) ],
		575 : [ ( 'hand', VarInt ) ],
		578 : [ ( 'hand', VarInt ) ],
		709 : [ ( 'hand', VarInt ) ],
		734 : [ ( 'hand', VarInt ) ],
		735 : [ ( 'hand', VarInt ) ],
		736 : [ ( 'hand', VarInt ) ],
		751 : [ ( 'hand', VarInt ) ],
		755 : [ ( 'hand', VarInt ) ],
		756 : [ ( 'hand', VarInt ) ],
		757 : [ ( 'hand', VarInt ) ],
		758 : [ ( 'hand', VarInt ) ],
		759 : [ ( 'hand', VarInt ) ],
		760 : [ ( 'hand', VarInt ) ],
		761 : [ ( 'hand', VarInt ) ]
	}
