"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *
from ....primitives import *

class PacketHideMessage(Packet):
	__slots__ = ( 'id', 'id', 'signature' )
	
	id : int
	signature : Union[Union[None, bytes],bytes]

	def __init__(self, 
		id:int | None = None,
		signature:Union[Union[None, bytes],bytes] | None = None,
		**kwargs
	):
		super().__init__(
			id=id,
			signature=signature
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		760 : 24,
		761 : 22
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		760 : [ ( 'signature', ByteArray ) ],
		761 : [ ( 'id', VarInt ), ( 'signature', SwitchType('id', { 0 : ByteArray }, None, ) ) ]
	}
