"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *
from ....primitives import *

class PacketWorldParticles(Packet):
	__slots__ = ( 'id', 'data', 'longDistance', 'offsetX', 'offsetY', 'offsetZ', 'particleData', 'particleId', 'particles', 'x', 'y', 'z' )
	
	data : Union[Union[Item, None, int],Union[None, list],bytes]
	longDistance : bool
	offsetX : float
	offsetY : float
	offsetZ : float
	particleData : float
	particleId : int
	particles : int
	x : float
	y : float
	z : float

	def __init__(self, 
		data:Union[Union[Item, None, int],Union[None, list],bytes] | None = None,
		longDistance:bool | None = None,
		offsetX:float | None = None,
		offsetY:float | None = None,
		offsetZ:float | None = None,
		particleData:float | None = None,
		particleId:int | None = None,
		particles:int | None = None,
		x:float | None = None,
		y:float | None = None,
		z:float | None = None,
		**kwargs
	):
		super().__init__(
			data=data,
			longDistance=longDistance,
			offsetX=offsetX,
			offsetY=offsetY,
			offsetZ=offsetZ,
			particleData=particleData,
			particleId=particleId,
			particles=particles,
			x=x,
			y=y,
			z=z
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		47 : 42,
		76 : 34,
		107 : 34,
		108 : 34,
		109 : 34,
		110 : 34,
		201 : 34,
		210 : 34,
		304 : 34,
		315 : 34,
		321 : 35,
		327 : 35,
		331 : 35,
		335 : 34,
		338 : 34,
		340 : 34,
		351 : 35,
		393 : 36,
		401 : 36,
		402 : 36,
		403 : 36,
		404 : 36,
		477 : 35,
		480 : 35,
		490 : 35,
		498 : 35,
		573 : 36,
		575 : 36,
		578 : 36,
		709 : 36,
		734 : 35,
		735 : 35,
		736 : 35,
		751 : 34,
		755 : 36,
		756 : 36,
		757 : 36,
		758 : 36,
		759 : 33,
		760 : 35,
		761 : 34
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		76 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		107 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		108 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		109 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		110 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		201 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		210 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		304 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		315 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		321 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		327 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		331 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		335 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		338 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		340 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : ArrayType(VarInt, 2, ), 37 : ArrayType(VarInt, 1, ), 38 : ArrayType(VarInt, 1, ) }, None, ) ) ],
		351 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', SwitchType('particleId', { 36 : Slot, 37 : VarInt, 38 : VarInt, 46 : VarInt }, None, ) ) ],
		393 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		401 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		402 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		403 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		404 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		477 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		480 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		490 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		498 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Float ), ( 'y', Float ), ( 'z', Float ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		573 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		575 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		578 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		709 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		734 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		735 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		736 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		751 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		755 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		756 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		757 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		758 : [ ( 'particleId', Int ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		759 : [ ( 'particleId', VarInt ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		760 : [ ( 'particleId', VarInt ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ],
		761 : [ ( 'particleId', VarInt ), ( 'longDistance', Boolean ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'offsetX', Float ), ( 'offsetY', Float ), ( 'offsetZ', Float ), ( 'particleData', Float ), ( 'particles', Int ), ( 'data', TrailingData ) ]
	}
