"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketPrepareCraftingGrid(Packet):
	__slots__ = ( 'id', 'returnEntry', 'actionNumber', 'prepareEntry', 'windowId' )
	
	returnEntry : list
	actionNumber : int
	prepareEntry : list
	windowId : int

	_state : int = 3

	_ids : Dict[int, int] = {
		321 : 1,
		327 : 1,
		331 : 1,
		335 : 1
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		321 : [ ( 'windowId', Byte ), ( 'actionNumber', UnsignedShort ), ( 'returnEntry', ArrayType(StructType(( 'item', Slot ), ( 'craftingSlot', Byte ), ( 'playerSlot', Byte ), ), Byte, ) ), ( 'prepareEntry', ArrayType(StructType(( 'item', Slot ), ( 'craftingSlot', Byte ), ( 'playerSlot', Byte ), ), Byte, ) ) ],
		327 : [ ( 'windowId', Byte ), ( 'actionNumber', UnsignedShort ), ( 'returnEntry', ArrayType(StructType(( 'item', Slot ), ( 'craftingSlot', Byte ), ( 'playerSlot', Byte ), ), UnsignedShort, ) ), ( 'prepareEntry', ArrayType(StructType(( 'item', Slot ), ( 'craftingSlot', Byte ), ( 'playerSlot', Byte ), ), UnsignedShort, ) ) ],
		331 : [ ( 'windowId', Byte ), ( 'actionNumber', UnsignedShort ), ( 'returnEntry', ArrayType(StructType(( 'item', Slot ), ( 'craftingSlot', Byte ), ( 'playerSlot', Byte ), ), UnsignedShort, ) ), ( 'prepareEntry', ArrayType(StructType(( 'item', Slot ), ( 'craftingSlot', Byte ), ( 'playerSlot', Byte ), ), UnsignedShort, ) ) ],
		335 : [ ( 'windowId', Byte ), ( 'actionNumber', UnsignedShort ), ( 'returnEntry', ArrayType(StructType(( 'item', Slot ), ( 'craftingSlot', Byte ), ( 'playerSlot', Byte ), ), UnsignedShort, ) ), ( 'prepareEntry', ArrayType(StructType(( 'item', Slot ), ( 'craftingSlot', Byte ), ( 'playerSlot', Byte ), ), UnsignedShort, ) ) ]
	}
