"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....definitions import *
from ....types import *

class PacketBlockPlace(Packet):
	__slots__ = ( 'id', 'cursorX', 'cursorY', 'cursorZ', 'direction', 'hand', 'heldItem', 'insideBlock', 'location' )
	
	cursorX : Union[float,int]
	cursorY : Union[float,int]
	cursorZ : Union[float,int]
	direction : int
	hand : int
	heldItem : dict
	insideBlock : bool
	location : tuple

	def __init__(self, proto:int,
		cursorX:Union[float,int]=None,
		cursorY:Union[float,int]=None,
		cursorZ:Union[float,int]=None,
		direction:int=None,
		hand:int=None,
		heldItem:dict=None,
		insideBlock:bool=None,
		location:tuple=None,
		**kwargs
	):
		super().__init__(proto,
			cursorX=cursorX,
			cursorY=cursorY,
			cursorZ=cursorZ,
			direction=direction,
			hand=hand,
			heldItem=heldItem,
			insideBlock=insideBlock,
			location=location
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		47 : 8,
		76 : 25,
		107 : 28,
		108 : 28,
		109 : 28,
		110 : 28,
		201 : 28,
		210 : 28,
		304 : 28,
		315 : 28,
		321 : 30,
		327 : 30,
		331 : 30,
		335 : 31,
		338 : 31,
		340 : 31,
		351 : 31,
		393 : 41,
		401 : 41,
		402 : 41,
		403 : 41,
		404 : 41,
		477 : 44,
		480 : 44,
		490 : 44,
		498 : 44,
		573 : 44,
		575 : 44,
		578 : 44,
		709 : 44,
		734 : 45,
		735 : 45,
		736 : 45,
		751 : 46,
		755 : 46,
		756 : 46,
		757 : 46
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'location', Position ), ( 'direction', Byte ), ( 'heldItem', Slot ), ( 'cursorX', Byte ), ( 'cursorY', Byte ), ( 'cursorZ', Byte ) ],
		76 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Byte ), ( 'cursorY', Byte ), ( 'cursorZ', Byte ) ],
		107 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Byte ), ( 'cursorY', Byte ), ( 'cursorZ', Byte ) ],
		108 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Byte ), ( 'cursorY', Byte ), ( 'cursorZ', Byte ) ],
		109 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Byte ), ( 'cursorY', Byte ), ( 'cursorZ', Byte ) ],
		110 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Byte ), ( 'cursorY', Byte ), ( 'cursorZ', Byte ) ],
		201 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Byte ), ( 'cursorY', Byte ), ( 'cursorZ', Byte ) ],
		210 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Byte ), ( 'cursorY', Byte ), ( 'cursorZ', Byte ) ],
		304 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Byte ), ( 'cursorY', Byte ), ( 'cursorZ', Byte ) ],
		315 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ) ],
		321 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ) ],
		327 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ) ],
		331 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ) ],
		335 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ) ],
		338 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ) ],
		340 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ) ],
		351 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ) ],
		393 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ) ],
		401 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ) ],
		402 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ) ],
		403 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ) ],
		404 : [ ( 'location', Position ), ( 'direction', VarInt ), ( 'hand', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ) ],
		477 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		480 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		490 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		498 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		573 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		575 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		578 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		709 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		734 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		735 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		736 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		751 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		755 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		756 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ],
		757 : [ ( 'hand', VarInt ), ( 'location', Position ), ( 'direction', VarInt ), ( 'cursorX', Float ), ( 'cursorY', Float ), ( 'cursorZ', Float ), ( 'insideBlock', Boolean ) ]
	}
