"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....definitions import *
from ....types import *

class PacketMessageAcknowledgement(Packet):
	__slots__ = ( 'id', 'count', 'lastRejectedMessage', 'previousMessages' )
	
	count : int
	lastRejectedMessage : tuple
	previousMessages : bytes

	def __init__(self, proto:int,
		count:int=None,
		lastRejectedMessage:tuple=None,
		previousMessages:bytes=None,
		**kwargs
	):
		super().__init__(proto,
			count=count,
			lastRejectedMessage=lastRejectedMessage,
			previousMessages=previousMessages
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		760 : 3,
		761 : 3
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		760 : [ ( 'previousMessages', TrailingData ), ( 'lastRejectedMessage', OptionalType(StructType(( 'sender', UUID ), ( 'signature', ByteArray ), ), ) ) ],
		761 : [ ( 'count', VarInt ) ]
	}
