"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketPickItem(Packet):
	__slots__ = ( 'id', 'slot' )
	
	slot : int

	def __init__(self, proto:int,
		slot:int=None
	):
		super().__init__(proto,
			slot=slot
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		393 : 21,
		401 : 21,
		402 : 21,
		403 : 21,
		404 : 21,
		477 : 23,
		480 : 23,
		490 : 23,
		498 : 23,
		573 : 23,
		575 : 23,
		578 : 23,
		709 : 23,
		734 : 24,
		735 : 24,
		736 : 24,
		751 : 24,
		755 : 23,
		756 : 23,
		757 : 23
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		393 : [ ( 'slot', VarInt ) ],
		401 : [ ( 'slot', VarInt ) ],
		402 : [ ( 'slot', VarInt ) ],
		403 : [ ( 'slot', VarInt ) ],
		404 : [ ( 'slot', VarInt ) ],
		477 : [ ( 'slot', VarInt ) ],
		480 : [ ( 'slot', VarInt ) ],
		490 : [ ( 'slot', VarInt ) ],
		498 : [ ( 'slot', VarInt ) ],
		573 : [ ( 'slot', VarInt ) ],
		575 : [ ( 'slot', VarInt ) ],
		578 : [ ( 'slot', VarInt ) ],
		709 : [ ( 'slot', VarInt ) ],
		734 : [ ( 'slot', VarInt ) ],
		735 : [ ( 'slot', VarInt ) ],
		736 : [ ( 'slot', VarInt ) ],
		751 : [ ( 'slot', VarInt ) ],
		755 : [ ( 'slot', VarInt ) ],
		756 : [ ( 'slot', VarInt ) ],
		757 : [ ( 'slot', VarInt ) ]
	}
