"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....definitions import *
from ....types import *

class PacketQueryEntityNbt(Packet):
	__slots__ = ( 'id', 'entityId', 'transactionId' )
	
	entityId : int
	transactionId : int

	def __init__(self, proto:int,
		entityId:int=None,
		transactionId:int=None,
		**kwargs
	):
		super().__init__(proto,
			entityId=entityId,
			transactionId=transactionId
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		393 : 12,
		401 : 12,
		402 : 12,
		403 : 12,
		404 : 12,
		477 : 13,
		480 : 13,
		490 : 13,
		498 : 13,
		573 : 13,
		575 : 13,
		578 : 13,
		709 : 13,
		734 : 13,
		735 : 13,
		736 : 13,
		751 : 13,
		755 : 12,
		756 : 12,
		757 : 12,
		758 : 12,
		759 : 14,
		760 : 15,
		761 : 14
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		393 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		401 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		402 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		403 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		404 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		477 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		480 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		490 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		498 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		573 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		575 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		578 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		709 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		734 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		735 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		736 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		751 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		755 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		756 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		757 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		758 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		759 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		760 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ],
		761 : [ ( 'transactionId', VarInt ), ( 'entityId', VarInt ) ]
	}
