"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *

class PacketWindowClick(Packet):
	__slots__ = ( 'id', 'action', 'changedSlots', 'cursorItem', 'item', 'mode', 'mouseButton', 'slot', 'stateId', 'windowId' )
	
	action : int
	changedSlots : list
	cursorItem : dict
	item : dict
	mode : int
	mouseButton : int
	slot : int
	stateId : int
	windowId : int

	def __init__(self, proto:int,
		action:int=None,
		changedSlots:list=None,
		cursorItem:dict=None,
		item:dict=None,
		mode:int=None,
		mouseButton:int=None,
		slot:int=None,
		stateId:int=None,
		windowId:int=None,
		**kwargs
	):
		super().__init__(proto,
			action=action,
			changedSlots=changedSlots,
			cursorItem=cursorItem,
			item=item,
			mode=mode,
			mouseButton=mouseButton,
			slot=slot,
			stateId=stateId,
			windowId=windowId
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		47 : 14,
		76 : 6,
		107 : 7,
		108 : 7,
		109 : 7,
		110 : 7,
		201 : 7,
		210 : 7,
		304 : 7,
		315 : 7,
		321 : 8,
		327 : 8,
		331 : 8,
		335 : 8,
		338 : 7,
		340 : 7,
		351 : 7,
		393 : 8,
		401 : 8,
		402 : 8,
		403 : 8,
		404 : 8,
		477 : 9,
		480 : 9,
		490 : 9,
		498 : 9,
		573 : 9,
		575 : 9,
		578 : 9,
		709 : 9,
		734 : 9,
		735 : 9,
		736 : 9,
		751 : 9,
		755 : 8,
		756 : 8,
		757 : 8
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		76 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		107 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		108 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		109 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		110 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		201 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		210 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		304 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		315 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		321 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		327 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		331 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		335 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		338 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		340 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		351 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		393 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		401 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		402 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		403 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		404 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		477 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		480 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		490 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		498 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		573 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		575 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		578 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		709 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		734 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		735 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		736 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		751 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'action', Short ), ( 'mode', Byte ), ( 'item', Slot ) ],
		755 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'mode', Byte ), ( 'changedSlots', ArrayType(StructType(( 'location', Short ), ( 'item', Slot ), ), VarInt, ) ), ( 'cursorItem', Slot ) ],
		756 : [ ( 'windowId', Byte ), ( 'stateId', VarInt ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'mode', VarInt ), ( 'changedSlots', ArrayType(StructType(( 'location', Short ), ( 'item', Slot ), ), VarInt, ) ), ( 'cursorItem', Slot ) ],
		757 : [ ( 'windowId', Byte ), ( 'stateId', VarInt ), ( 'slot', Short ), ( 'mouseButton', Byte ), ( 'mode', VarInt ), ( 'changedSlots', ArrayType(StructType(( 'location', Short ), ( 'item', Slot ), ), VarInt, ) ), ( 'cursorItem', Slot ) ]
	}
