"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketRecipeBook(Packet):
	__slots__ = ( 'id', 'bookOpen', 'filterActive', 'bookId' )
	
	bookOpen : bool
	filterActive : bool
	bookId : int

	_state : int = 3

	_ids : Dict[int, int] = {
		751 : 30,
		755 : 30,
		756 : 30,
		757 : 30,
		1073741839 : 31
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		751 : [ ( 'bookId', VarInt ), ( 'bookOpen', Boolean ), ( 'filterActive', Boolean ) ],
		755 : [ ( 'bookId', VarInt ), ( 'bookOpen', Boolean ), ( 'filterActive', Boolean ) ],
		756 : [ ( 'bookId', VarInt ), ( 'bookOpen', Boolean ), ( 'filterActive', Boolean ) ],
		757 : [ ( 'bookId', VarInt ), ( 'bookOpen', Boolean ), ( 'filterActive', Boolean ) ],
		1073741839 : [ ( 'bookId', VarInt ), ( 'bookOpen', Boolean ), ( 'filterActive', Boolean ) ]
	}
