"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketDisplayedRecipe(Packet):
	__slots__ = ( 'id', 'recipeId' )
	
	recipeId : str

	_state : int = 3

	_ids : Dict[int, int] = {
		751 : 31,
		755 : 31,
		756 : 31,
		757 : 31,
		1073741839 : 30
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		751 : [ ( 'recipeId', String ) ],
		755 : [ ( 'recipeId', String ) ],
		756 : [ ( 'recipeId', String ) ],
		757 : [ ( 'recipeId', String ) ],
		1073741839 : [ ( 'recipeId', String ) ]
	}
