"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketGenerateStructure(Packet):
	__slots__ = ( 'id', 'keepJigsaws', 'levels', 'location' )
	
	keepJigsaws : bool
	levels : int
	location : tuple

	def __init__(self, proto:int,
		keepJigsaws:bool=None,
		levels:int=None,
		location:tuple=None
	):
		super().__init__(proto,
			keepJigsaws=keepJigsaws,
			levels=levels,
			location=location
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		734 : 15,
		735 : 15,
		736 : 15,
		751 : 15,
		755 : 14,
		756 : 14,
		757 : 14
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		734 : [ ( 'location', Position ), ( 'levels', VarInt ), ( 'keepJigsaws', Boolean ) ],
		735 : [ ( 'location', Position ), ( 'levels', VarInt ), ( 'keepJigsaws', Boolean ) ],
		736 : [ ( 'location', Position ), ( 'levels', VarInt ), ( 'keepJigsaws', Boolean ) ],
		751 : [ ( 'location', Position ), ( 'levels', VarInt ), ( 'keepJigsaws', Boolean ) ],
		755 : [ ( 'location', Position ), ( 'levels', VarInt ), ( 'keepJigsaws', Boolean ) ],
		756 : [ ( 'location', Position ), ( 'levels', VarInt ), ( 'keepJigsaws', Boolean ) ],
		757 : [ ( 'location', Position ), ( 'levels', VarInt ), ( 'keepJigsaws', Boolean ) ]
	}
