"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *

class PacketLook(Packet):
	__slots__ = ( 'id', 'onGround', 'pitch', 'yaw' )
	
	onGround : bool
	pitch : float
	yaw : float

	def __init__(self, proto:int,
		onGround:bool=None,
		pitch:float=None,
		yaw:float=None,
		**kwargs
	):
		super().__init__(proto,
			onGround=onGround,
			pitch=pitch,
			yaw=yaw
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		47 : 5,
		76 : 13,
		107 : 14,
		108 : 14,
		109 : 14,
		110 : 14,
		201 : 14,
		210 : 14,
		304 : 14,
		315 : 14,
		321 : 15,
		327 : 15,
		331 : 15,
		335 : 16,
		338 : 15,
		340 : 15,
		351 : 15,
		393 : 18,
		401 : 18,
		402 : 18,
		403 : 18,
		404 : 18,
		477 : 19,
		480 : 19,
		490 : 19,
		498 : 19,
		573 : 19,
		575 : 19,
		578 : 19,
		709 : 19,
		734 : 20,
		735 : 20,
		736 : 20,
		751 : 20,
		755 : 19,
		756 : 19,
		757 : 19
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		76 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		107 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		108 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		109 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		110 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		201 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		210 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		304 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		315 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		321 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		327 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		331 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		335 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		338 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		340 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		351 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		393 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		401 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		402 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		403 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		404 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		477 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		480 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		490 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		498 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		573 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		575 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		578 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		709 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		734 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		735 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		736 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		751 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		755 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		756 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ],
		757 : [ ( 'yaw', Float ), ( 'pitch', Float ), ( 'onGround', Boolean ) ]
	}
