"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketEnchantItem(Packet):
	__slots__ = ( 'id', 'windowId', 'enchantment' )
	
	windowId : int
	enchantment : int

	_state : int = 3

	_ids : Dict[int, int] = {
		5 : 17,
		47 : 17,
		76 : 5,
		107 : 6,
		108 : 6,
		109 : 6,
		110 : 6,
		201 : 6,
		210 : 6,
		304 : 6,
		315 : 6,
		321 : 7,
		327 : 7,
		331 : 7,
		335 : 7,
		338 : 6,
		340 : 6,
		351 : 6,
		393 : 7,
		401 : 7,
		402 : 7,
		403 : 7,
		404 : 7,
		477 : 8,
		480 : 8,
		490 : 8,
		498 : 8,
		573 : 8,
		575 : 8,
		578 : 8,
		709 : 8,
		734 : 8,
		735 : 8,
		736 : 8,
		751 : 8,
		755 : 7,
		756 : 7,
		757 : 7,
		1073741839 : 8
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		5 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		47 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		76 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		107 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		108 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		109 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		110 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		201 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		210 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		304 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		315 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		321 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		327 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		331 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		335 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		338 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		340 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		351 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		393 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		401 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		402 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		403 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		404 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		477 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		480 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		490 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		498 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		573 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		575 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		578 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		709 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		734 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		735 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		736 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		751 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		755 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		756 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		757 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ],
		1073741839 : [ ( 'windowId', Byte ), ( 'enchantment', Byte ) ]
	}
