"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *
from ....primitives import *

class PacketWorldBorderCenter(Packet):
	__slots__ = ( 'id', 'x', 'z' )
	
	x : float
	z : float

	def __init__(self, 
		x:float | None = None,
		z:float | None = None,
		**kwargs
	):
		super().__init__(
			x=x,
			z=z
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		755 : 66,
		756 : 66,
		757 : 66,
		758 : 66,
		759 : 65,
		760 : 68,
		761 : 67
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		755 : [ ( 'x', Double ), ( 'z', Double ) ],
		756 : [ ( 'x', Double ), ( 'z', Double ) ],
		757 : [ ( 'x', Double ), ( 'z', Double ) ],
		758 : [ ( 'x', Double ), ( 'z', Double ) ],
		759 : [ ( 'x', Double ), ( 'z', Double ) ],
		760 : [ ( 'x', Double ), ( 'z', Double ) ],
		761 : [ ( 'x', Double ), ( 'z', Double ) ]
	}
