"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *
from ....primitives import *

class PacketWorldBorderWarningDelay(Packet):
	__slots__ = ( 'id', 'warningTime' )
	
	warningTime : int

	def __init__(self, 
		warningTime:int | None = None,
		**kwargs
	):
		super().__init__(
			warningTime=warningTime
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		755 : 69,
		756 : 69,
		757 : 69,
		758 : 69,
		759 : 68,
		760 : 71,
		761 : 70
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		755 : [ ( 'warningTime', VarInt ) ],
		756 : [ ( 'warningTime', VarInt ) ],
		757 : [ ( 'warningTime', VarInt ) ],
		758 : [ ( 'warningTime', VarInt ) ],
		759 : [ ( 'warningTime', VarInt ) ],
		760 : [ ( 'warningTime', VarInt ) ],
		761 : [ ( 'warningTime', VarInt ) ]
	}
