"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *
from ....primitives import *

class PacketWorldBorderWarningReach(Packet):
	__slots__ = ( 'id', 'warningBlocks' )
	
	warningBlocks : int

	def __init__(self, 
		warningBlocks:int | None = None,
		**kwargs
	):
		super().__init__(
			warningBlocks=warningBlocks
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		755 : 70,
		756 : 70,
		757 : 70,
		758 : 70,
		759 : 69,
		760 : 72,
		761 : 71
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		755 : [ ( 'warningBlocks', VarInt ) ],
		756 : [ ( 'warningBlocks', VarInt ) ],
		757 : [ ( 'warningBlocks', VarInt ) ],
		758 : [ ( 'warningBlocks', VarInt ) ],
		759 : [ ( 'warningBlocks', VarInt ) ],
		760 : [ ( 'warningBlocks', VarInt ) ],
		761 : [ ( 'warningBlocks', VarInt ) ]
	}
