"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *
from ....primitives import *

class PacketMessageHeader(Packet):
	__slots__ = ( 'id', 'messageHash', 'previousSignature', 'senderUuid', 'signature' )
	
	messageHash : bytes
	previousSignature : tuple
	senderUuid : str
	signature : bytes

	def __init__(self, 
		messageHash:bytes | None = None,
		previousSignature:tuple | None = None,
		senderUuid:str | None = None,
		signature:bytes | None = None,
		**kwargs
	):
		super().__init__(
			messageHash=messageHash,
			previousSignature=previousSignature,
			senderUuid=senderUuid,
			signature=signature
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		760 : 50
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		760 : [ ( 'previousSignature', OptionalType(ByteArray, ) ), ( 'senderUuid', UUID ), ( 'signature', ByteArray ), ( 'messageHash', ByteArray ) ]
	}
