"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *
from ....primitives import *

class PacketChatMessage(Packet):
	__slots__ = ( 'id', 'acknowledged', 'lastRejectedMessage', 'message', 'offset', 'previousMessages', 'salt', 'signature', 'signedPreview', 'timestamp' )
	
	acknowledged : bytes
	lastRejectedMessage : tuple
	message : str
	offset : int
	previousMessages : bytes
	salt : int
	signature : Union[bytes,tuple]
	signedPreview : bool
	timestamp : int

	def __init__(self, 
		acknowledged:bytes | None = None,
		lastRejectedMessage:tuple | None = None,
		message:str | None = None,
		offset:int | None = None,
		previousMessages:bytes | None = None,
		salt:int | None = None,
		signature:Union[bytes,tuple] | None = None,
		signedPreview:bool | None = None,
		timestamp:int | None = None,
		**kwargs
	):
		super().__init__(
			acknowledged=acknowledged,
			lastRejectedMessage=lastRejectedMessage,
			message=message,
			offset=offset,
			previousMessages=previousMessages,
			salt=salt,
			signature=signature,
			signedPreview=signedPreview,
			timestamp=timestamp
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		759 : 4,
		760 : 5,
		761 : 5
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		759 : [ ( 'message', String ), ( 'timestamp', Long ), ( 'salt', Long ), ( 'signature', ByteArray ), ( 'signedPreview', Boolean ) ],
		760 : [ ( 'message', String ), ( 'timestamp', Long ), ( 'salt', Long ), ( 'signature', ByteArray ), ( 'signedPreview', Boolean ), ( 'previousMessages', TrailingData ), ( 'lastRejectedMessage', OptionalType(StructType(( 'sender', UUID ), ( 'signature', ByteArray ), ), ) ) ],
		761 : [ ( 'message', String ), ( 'timestamp', Long ), ( 'salt', Long ), ( 'signature', OptionalType(ByteArray, ) ), ( 'offset', VarInt ), ( 'acknowledged', ByteArray ) ]
	}
