"""[!] This file is autogenerated"""

from .packet_disconnect import PacketDisconnect
from .packet_encryption_begin import PacketEncryptionBegin
from .packet_success import PacketSuccess
from .packet_compress import PacketCompress
from .packet_login_plugin_request import PacketLoginPluginRequest

REGISTRY = {
	757 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	498 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	335 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	315 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	109 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	401 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	76 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	340 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	338 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	351 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	756 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	490 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	573 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	477 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	736 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	393 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	402 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	331 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	735 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	47 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	734 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	403 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	755 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	575 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	201 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	480 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	107 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	210 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	304 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	321 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	327 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	578 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	108 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	404 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	709 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest },
	110 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress },
	751 : { 0:PacketDisconnect, 1:PacketEncryptionBegin, 2:PacketSuccess, 3:PacketCompress, 4:PacketLoginPluginRequest }
}
