"""[!] This file is autogenerated"""

from .packet_login_start import PacketLoginStart
from .packet_encryption_begin import PacketEncryptionBegin
from .packet_login_plugin_response import PacketLoginPluginResponse

REGISTRY = {
	47 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	76 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	107 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	108 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	109 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	110 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	201 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	210 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	304 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	315 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	321 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	327 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	331 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	335 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	338 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	340 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	351 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin },
	393 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	401 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	402 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	403 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	404 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	477 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	480 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	490 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	498 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	573 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	575 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	578 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	709 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	734 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	735 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	736 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	751 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	755 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	756 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	757 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	758 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	759 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	760 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse },
	761 : { 0 : PacketLoginStart, 1 : PacketEncryptionBegin, 2 : PacketLoginPluginResponse }
}
