"""[!] This file is autogenerated"""

from .packet_login_start import PacketLoginStart
from .packet_encryption_begin import PacketEncryptionBegin
from .packet_login_plugin_response import PacketLoginPluginResponse

REGISTRY = {
	304 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	201 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	47 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	498 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	315 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	107 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	755 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	477 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	757 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	327 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	351 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	1073741839 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	736 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	573 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	404 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	393 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	335 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	338 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	331 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	480 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	735 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	109 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	709 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	340 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	5 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	490 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	734 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	210 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	110 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	578 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	403 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	108 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	575 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	76 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	751 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	756 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	321 : { 0:PacketLoginStart, 1:PacketEncryptionBegin },
	402 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse },
	401 : { 0:PacketLoginStart, 1:PacketEncryptionBegin, 2:PacketLoginPluginResponse }
}
