"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....definitions import *
from ....types import *

class PacketLoginStart(Packet):
	__slots__ = ( 'id', 'playerUUID', 'signature', 'username' )
	
	playerUUID : tuple
	signature : tuple
	username : str

	def __init__(self, proto:int,
		playerUUID:tuple=None,
		signature:tuple=None,
		username:str=None,
		**kwargs
	):
		super().__init__(proto,
			playerUUID=playerUUID,
			signature=signature,
			username=username
		)

	_state : int = 2

	_ids : Dict[int, int] = {
		47 : 0,
		76 : 0,
		107 : 0,
		108 : 0,
		109 : 0,
		110 : 0,
		201 : 0,
		210 : 0,
		304 : 0,
		315 : 0,
		321 : 0,
		327 : 0,
		331 : 0,
		335 : 0,
		338 : 0,
		340 : 0,
		351 : 0,
		393 : 0,
		401 : 0,
		402 : 0,
		403 : 0,
		404 : 0,
		477 : 0,
		480 : 0,
		490 : 0,
		498 : 0,
		573 : 0,
		575 : 0,
		578 : 0,
		709 : 0,
		734 : 0,
		735 : 0,
		736 : 0,
		751 : 0,
		755 : 0,
		756 : 0,
		757 : 0,
		758 : 0,
		759 : 0,
		760 : 0,
		761 : 0
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'username', String ) ],
		76 : [ ( 'username', String ) ],
		107 : [ ( 'username', String ) ],
		108 : [ ( 'username', String ) ],
		109 : [ ( 'username', String ) ],
		110 : [ ( 'username', String ) ],
		201 : [ ( 'username', String ) ],
		210 : [ ( 'username', String ) ],
		304 : [ ( 'username', String ) ],
		315 : [ ( 'username', String ) ],
		321 : [ ( 'username', String ) ],
		327 : [ ( 'username', String ) ],
		331 : [ ( 'username', String ) ],
		335 : [ ( 'username', String ) ],
		338 : [ ( 'username', String ) ],
		340 : [ ( 'username', String ) ],
		351 : [ ( 'username', String ) ],
		393 : [ ( 'username', String ) ],
		401 : [ ( 'username', String ) ],
		402 : [ ( 'username', String ) ],
		403 : [ ( 'username', String ) ],
		404 : [ ( 'username', String ) ],
		477 : [ ( 'username', String ) ],
		480 : [ ( 'username', String ) ],
		490 : [ ( 'username', String ) ],
		498 : [ ( 'username', String ) ],
		573 : [ ( 'username', String ) ],
		575 : [ ( 'username', String ) ],
		578 : [ ( 'username', String ) ],
		709 : [ ( 'username', String ) ],
		734 : [ ( 'username', String ) ],
		735 : [ ( 'username', String ) ],
		736 : [ ( 'username', String ) ],
		751 : [ ( 'username', String ) ],
		755 : [ ( 'username', String ) ],
		756 : [ ( 'username', String ) ],
		757 : [ ( 'username', String ) ],
		758 : [ ( 'username', String ) ],
		759 : [ ( 'username', String ), ( 'signature', OptionalType(StructType(( 'timestamp', Long ), ( 'publicKey', ByteArray ), ( 'signature', ByteArray ), ), ) ) ],
		760 : [ ( 'username', String ), ( 'signature', OptionalType(StructType(( 'timestamp', Long ), ( 'publicKey', ByteArray ), ( 'signature', ByteArray ), ), ) ), ( 'playerUUID', OptionalType(UUID, ) ) ],
		761 : [ ( 'username', String ), ( 'playerUUID', OptionalType(UUID, ) ) ]
	}
