"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketWorldBorderCenter(Packet):
	__slots__ = ( 'id', 'z', 'x' )
	
	z : float
	x : float

	_state : int = 3

	_ids : Dict[int, int] = {
		755 : 66,
		756 : 66,
		757 : 66
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		755 : [ ( 'x', Double ), ( 'z', Double ) ],
		756 : [ ( 'x', Double ), ( 'z', Double ) ],
		757 : [ ( 'x', Double ), ( 'z', Double ) ]
	}
