"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketTileEntityData(Packet):
	__slots__ = ( 'id', 'action', 'nbtData', 'location' )
	
	action : int
	nbtData : bytes
	location : Union[tuple,bytes]

	_state : int = 3

	_ids : Dict[int, int] = {
		5 : 53,
		47 : 53,
		76 : 9,
		107 : 9,
		108 : 9,
		109 : 9,
		110 : 9,
		201 : 9,
		210 : 9,
		304 : 9,
		315 : 9,
		321 : 10,
		327 : 10,
		331 : 10,
		335 : 9,
		338 : 9,
		340 : 9,
		351 : 9,
		393 : 9,
		401 : 9,
		402 : 9,
		403 : 9,
		404 : 9,
		477 : 9,
		480 : 9,
		490 : 9,
		498 : 9,
		573 : 10,
		575 : 10,
		578 : 10,
		709 : 10,
		734 : 9,
		735 : 9,
		736 : 9,
		751 : 9,
		755 : 10,
		756 : 10,
		757 : 10,
		1073741839 : 10
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		5 : [ ( 'location', TrailingData ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		47 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		76 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		107 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		108 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		109 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		110 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		201 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		210 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		304 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		315 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		321 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		327 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		331 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		335 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		338 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		340 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		351 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		393 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		401 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		402 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		403 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		404 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		477 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		480 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		490 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		498 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		573 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		575 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		578 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		709 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		734 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		735 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		736 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		751 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		755 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		756 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ],
		757 : [ ( 'location', Position ), ( 'action', VarInt ), ( 'nbtData', TrailingData ) ],
		1073741839 : [ ( 'location', Position ), ( 'action', Byte ), ( 'nbtData', TrailingData ) ]
	}
