"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *

class PacketKickDisconnect(Packet):
	__slots__ = ( 'id', 'reason' )
	
	reason : str

	def __init__(self, proto:int,
		reason:str=None
	):
		super().__init__(proto,
			reason=reason
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		47 : 64,
		76 : 25,
		107 : 26,
		108 : 26,
		109 : 26,
		110 : 26,
		201 : 26,
		210 : 26,
		304 : 26,
		315 : 26,
		321 : 27,
		327 : 27,
		331 : 27,
		335 : 26,
		338 : 26,
		340 : 26,
		351 : 27,
		393 : 27,
		401 : 27,
		402 : 27,
		403 : 27,
		404 : 27,
		477 : 26,
		480 : 26,
		490 : 26,
		498 : 26,
		573 : 27,
		575 : 27,
		578 : 27,
		709 : 27,
		734 : 26,
		735 : 26,
		736 : 26,
		751 : 25,
		755 : 26,
		756 : 26,
		757 : 26
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'reason', String ) ],
		76 : [ ( 'reason', String ) ],
		107 : [ ( 'reason', String ) ],
		108 : [ ( 'reason', String ) ],
		109 : [ ( 'reason', String ) ],
		110 : [ ( 'reason', String ) ],
		201 : [ ( 'reason', String ) ],
		210 : [ ( 'reason', String ) ],
		304 : [ ( 'reason', String ) ],
		315 : [ ( 'reason', String ) ],
		321 : [ ( 'reason', String ) ],
		327 : [ ( 'reason', String ) ],
		331 : [ ( 'reason', String ) ],
		335 : [ ( 'reason', String ) ],
		338 : [ ( 'reason', String ) ],
		340 : [ ( 'reason', String ) ],
		351 : [ ( 'reason', String ) ],
		393 : [ ( 'reason', String ) ],
		401 : [ ( 'reason', String ) ],
		402 : [ ( 'reason', String ) ],
		403 : [ ( 'reason', String ) ],
		404 : [ ( 'reason', String ) ],
		477 : [ ( 'reason', String ) ],
		480 : [ ( 'reason', String ) ],
		490 : [ ( 'reason', String ) ],
		498 : [ ( 'reason', String ) ],
		573 : [ ( 'reason', String ) ],
		575 : [ ( 'reason', String ) ],
		578 : [ ( 'reason', String ) ],
		709 : [ ( 'reason', String ) ],
		734 : [ ( 'reason', String ) ],
		735 : [ ( 'reason', String ) ],
		736 : [ ( 'reason', String ) ],
		751 : [ ( 'reason', String ) ],
		755 : [ ( 'reason', String ) ],
		756 : [ ( 'reason', String ) ],
		757 : [ ( 'reason', String ) ]
	}
