"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *

class PacketEndCombatEvent(Packet):
	__slots__ = ( 'id', 'duration', 'entityId' )
	
	duration : int
	entityId : int

	def __init__(self, proto:int,
		duration:int=None,
		entityId:int=None
	):
		super().__init__(proto,
			duration=duration,
			entityId=entityId
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		755 : 51,
		756 : 51,
		757 : 51
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		755 : [ ( 'duration', VarInt ), ( 'entityId', Int ) ],
		756 : [ ( 'duration', VarInt ), ( 'entityId', Int ) ],
		757 : [ ( 'duration', VarInt ), ( 'entityId', Int ) ]
	}
