"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *

class PacketDestroyEntity(Packet):
	__slots__ = ( 'id', 'entityId' )
	
	entityId : int

	def __init__(self, proto:int,
		entityId:int=None
	):
		super().__init__(proto,
			entityId=entityId
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		755 : 58
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		755 : [ ( 'entityId', VarInt ) ]
	}
