"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketInitializeWorldBorder(Packet):
	__slots__ = ( 'id', 'warningTime', 'x', 'newDiameter', 'oldDiameter', 'warningBlocks', 'z', 'portalTeleportBoundary', 'speed' )
	
	warningTime : int
	x : float
	newDiameter : float
	oldDiameter : float
	warningBlocks : int
	z : float
	portalTeleportBoundary : int
	speed : int

	_state : int = 3

	_ids : Dict[int, int] = {
		755 : 32,
		756 : 32,
		757 : 32
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		755 : [ ( 'x', Double ), ( 'z', Double ), ( 'oldDiameter', Double ), ( 'newDiameter', Double ), ( 'speed', VarInt ), ( 'portalTeleportBoundary', VarInt ), ( 'warningBlocks', VarInt ), ( 'warningTime', VarInt ) ],
		756 : [ ( 'x', Double ), ( 'z', Double ), ( 'oldDiameter', Double ), ( 'newDiameter', Double ), ( 'speed', VarInt ), ( 'portalTeleportBoundary', VarInt ), ( 'warningBlocks', VarInt ), ( 'warningTime', VarInt ) ],
		757 : [ ( 'x', Double ), ( 'z', Double ), ( 'oldDiameter', Double ), ( 'newDiameter', Double ), ( 'speed', VarInt ), ( 'portalTeleportBoundary', VarInt ), ( 'warningBlocks', VarInt ), ( 'warningTime', VarInt ) ]
	}
