"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *

class PacketSpawnEntityPainting(Packet):
	__slots__ = ( 'id', 'direction', 'entityId', 'entityUUID', 'location', 'title' )
	
	direction : int
	entityId : int
	entityUUID : str
	location : tuple
	title : Union[str,int]

	def __init__(self, proto:int,
		direction:int=None,
		entityId:int=None,
		entityUUID:str=None,
		location:tuple=None,
		title:Union[str,int]=None
	):
		super().__init__(proto,
			direction=direction,
			entityId=entityId,
			entityUUID=entityUUID,
			location=location,
			title=title
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		47 : 16,
		76 : 4,
		107 : 4,
		108 : 4,
		109 : 4,
		110 : 4,
		201 : 4,
		210 : 4,
		304 : 4,
		315 : 4,
		321 : 4,
		327 : 4,
		331 : 4,
		335 : 4,
		338 : 4,
		340 : 4,
		351 : 4,
		393 : 4,
		401 : 4,
		402 : 4,
		403 : 4,
		404 : 4,
		477 : 4,
		480 : 4,
		490 : 4,
		498 : 4,
		573 : 4,
		575 : 4,
		578 : 4,
		709 : 4,
		734 : 3,
		735 : 3,
		736 : 3,
		751 : 3,
		755 : 3,
		756 : 3,
		757 : 3
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'entityId', VarInt ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		76 : [ ( 'entityId', VarInt ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		107 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		108 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		109 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		110 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		201 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		210 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		304 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		315 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		321 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		327 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		331 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		335 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		338 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		340 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		351 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', String ), ( 'location', Position ), ( 'direction', Byte ) ],
		393 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		401 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		402 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		403 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		404 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		477 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		480 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		490 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		498 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		573 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		575 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		578 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		709 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		734 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		735 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		736 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		751 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		755 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		756 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ],
		757 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'title', VarInt ), ( 'location', Position ), ( 'direction', Byte ) ]
	}
