"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....definitions import *
from ....types import *

class PacketShouldDisplayChatPreview(Packet):
	__slots__ = ( 'id', 'should_display_chat_preview' )
	
	should_display_chat_preview : bool

	def __init__(self, proto:int,
		should_display_chat_preview:bool=None,
		**kwargs
	):
		super().__init__(proto,
			should_display_chat_preview=should_display_chat_preview
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		759 : 75,
		760 : 78
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		759 : [ ( 'should_display_chat_preview', Boolean ) ],
		760 : [ ( 'should_display_chat_preview', Boolean ) ]
	}
