"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *

class PacketBlockChange(Packet):
	__slots__ = ( 'id', 'location', 'type' )
	
	location : tuple
	type : int

	def __init__(self, proto:int,
		location:tuple=None,
		type:int=None,
		**kwargs
	):
		super().__init__(proto,
			location=location,
			type=type
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		47 : 35,
		76 : 11,
		107 : 11,
		108 : 11,
		109 : 11,
		110 : 11,
		201 : 11,
		210 : 11,
		304 : 11,
		315 : 11,
		321 : 12,
		327 : 12,
		331 : 12,
		335 : 11,
		338 : 11,
		340 : 11,
		351 : 11,
		393 : 11,
		401 : 11,
		402 : 11,
		403 : 11,
		404 : 11,
		477 : 11,
		480 : 11,
		490 : 11,
		498 : 11,
		573 : 12,
		575 : 12,
		578 : 12,
		709 : 12,
		734 : 11,
		735 : 11,
		736 : 11,
		751 : 11,
		755 : 12,
		756 : 12,
		757 : 12
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		76 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		107 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		108 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		109 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		110 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		201 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		210 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		304 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		315 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		321 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		327 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		331 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		335 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		338 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		340 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		351 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		393 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		401 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		402 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		403 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		404 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		477 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		480 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		490 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		498 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		573 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		575 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		578 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		709 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		734 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		735 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		736 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		751 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		755 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		756 : [ ( 'location', Position ), ( 'type', VarInt ) ],
		757 : [ ( 'location', Position ), ( 'type', VarInt ) ]
	}
