"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *

class PacketUpdateSign(Packet):
	__slots__ = ( 'id', 'location', 'text1', 'text2', 'text3', 'text4' )
	
	location : tuple
	text1 : str
	text2 : str
	text3 : str
	text4 : str

	def __init__(self, proto:int,
		location:tuple=None,
		text1:str=None,
		text2:str=None,
		text3:str=None,
		text4:str=None,
		**kwargs
	):
		super().__init__(proto,
			location=location,
			text1=text1,
			text2=text2,
			text3=text3,
			text4=text4
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		47 : 51,
		76 : 69,
		107 : 70,
		108 : 70,
		109 : 70
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'location', Position ), ( 'text1', String ), ( 'text2', String ), ( 'text3', String ), ( 'text4', String ) ],
		76 : [ ( 'location', Position ), ( 'text1', String ), ( 'text2', String ), ( 'text3', String ), ( 'text4', String ) ],
		107 : [ ( 'location', Position ), ( 'text1', String ), ( 'text2', String ), ( 'text3', String ), ( 'text4', String ) ],
		108 : [ ( 'location', Position ), ( 'text1', String ), ( 'text2', String ), ( 'text3', String ), ( 'text4', String ) ],
		109 : [ ( 'location', Position ), ( 'text1', String ), ( 'text2', String ), ( 'text3', String ), ( 'text4', String ) ]
	}
