"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *

class PacketWorldBorderSize(Packet):
	__slots__ = ( 'id', 'diameter' )
	
	diameter : float

	def __init__(self, proto:int,
		diameter:float=None,
		**kwargs
	):
		super().__init__(proto,
			diameter=diameter
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		755 : 68,
		756 : 68,
		757 : 68
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		755 : [ ( 'diameter', Double ) ],
		756 : [ ( 'diameter', Double ) ],
		757 : [ ( 'diameter', Double ) ]
	}
