"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketRespawn(Packet):
	__slots__ = ( 'id', 'copyMetadata', 'difficulty', 'dimension', 'gamemode', 'hashedSeed', 'isDebug', 'isFlat', 'levelType', 'previousGamemode', 'worldName' )
	
	copyMetadata : bool
	difficulty : int
	dimension : Union[int,bytes,str]
	gamemode : int
	hashedSeed : int
	isDebug : bool
	isFlat : bool
	levelType : str
	previousGamemode : int
	worldName : str

	def __init__(self, proto:int,
		copyMetadata:bool=None,
		difficulty:int=None,
		dimension:Union[int,bytes,str]=None,
		gamemode:int=None,
		hashedSeed:int=None,
		isDebug:bool=None,
		isFlat:bool=None,
		levelType:str=None,
		previousGamemode:int=None,
		worldName:str=None
	):
		super().__init__(proto,
			copyMetadata=copyMetadata,
			difficulty=difficulty,
			dimension=dimension,
			gamemode=gamemode,
			hashedSeed=hashedSeed,
			isDebug=isDebug,
			isFlat=isFlat,
			levelType=levelType,
			previousGamemode=previousGamemode,
			worldName=worldName
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		47 : 7,
		76 : 51,
		107 : 51,
		108 : 51,
		109 : 51,
		110 : 51,
		201 : 51,
		210 : 51,
		304 : 51,
		315 : 51,
		321 : 53,
		327 : 53,
		331 : 53,
		335 : 52,
		338 : 53,
		340 : 53,
		351 : 54,
		393 : 56,
		401 : 56,
		402 : 56,
		403 : 56,
		404 : 56,
		477 : 58,
		480 : 58,
		490 : 58,
		498 : 58,
		573 : 59,
		575 : 59,
		578 : 59,
		709 : 59,
		734 : 58,
		735 : 58,
		736 : 58,
		751 : 57,
		755 : 61,
		756 : 61,
		757 : 61
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		76 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		107 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		108 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		109 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		110 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		201 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		210 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		304 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		315 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		321 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		327 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		331 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		335 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		338 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		340 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		351 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		393 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		401 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		402 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		403 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		404 : [ ( 'dimension', Int ), ( 'difficulty', Byte ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		477 : [ ( 'dimension', Int ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		480 : [ ( 'dimension', Int ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		490 : [ ( 'dimension', Int ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		498 : [ ( 'dimension', Int ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		573 : [ ( 'dimension', Int ), ( 'hashedSeed', Long ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		575 : [ ( 'dimension', Int ), ( 'hashedSeed', Long ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		578 : [ ( 'dimension', Int ), ( 'hashedSeed', Long ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		709 : [ ( 'dimension', Int ), ( 'hashedSeed', Long ), ( 'gamemode', Byte ), ( 'levelType', String ) ],
		734 : [ ( 'dimension', String ), ( 'worldName', String ), ( 'hashedSeed', Long ), ( 'gamemode', Byte ), ( 'previousGamemode', Byte ), ( 'isDebug', Boolean ), ( 'isFlat', Boolean ), ( 'copyMetadata', Boolean ) ],
		735 : [ ( 'dimension', String ), ( 'worldName', String ), ( 'hashedSeed', Long ), ( 'gamemode', Byte ), ( 'previousGamemode', Byte ), ( 'isDebug', Boolean ), ( 'isFlat', Boolean ), ( 'copyMetadata', Boolean ) ],
		736 : [ ( 'dimension', String ), ( 'worldName', String ), ( 'hashedSeed', Long ), ( 'gamemode', Byte ), ( 'previousGamemode', Byte ), ( 'isDebug', Boolean ), ( 'isFlat', Boolean ), ( 'copyMetadata', Boolean ) ],
		751 : [ ( 'dimension', NBTTag ), ( 'worldName', String ), ( 'hashedSeed', Long ), ( 'gamemode', Byte ), ( 'previousGamemode', Byte ), ( 'isDebug', Boolean ), ( 'isFlat', Boolean ), ( 'copyMetadata', Boolean ) ],
		755 : [ ( 'dimension', NBTTag ), ( 'worldName', String ), ( 'hashedSeed', Long ), ( 'gamemode', Byte ), ( 'previousGamemode', Byte ), ( 'isDebug', Boolean ), ( 'isFlat', Boolean ), ( 'copyMetadata', Boolean ) ],
		756 : [ ( 'dimension', NBTTag ), ( 'worldName', String ), ( 'hashedSeed', Long ), ( 'gamemode', Byte ), ( 'previousGamemode', Byte ), ( 'isDebug', Boolean ), ( 'isFlat', Boolean ), ( 'copyMetadata', Boolean ) ],
		757 : [ ( 'dimension', NBTTag ), ( 'worldName', String ), ( 'hashedSeed', Long ), ( 'gamemode', Byte ), ( 'previousGamemode', Byte ), ( 'isDebug', Boolean ), ( 'isFlat', Boolean ), ( 'copyMetadata', Boolean ) ]
	}
