"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketWorldBorderLerpSize(Packet):
	__slots__ = ( 'id', 'oldDiameter', 'speed', 'newDiameter' )
	
	oldDiameter : float
	speed : int
	newDiameter : float

	_state : int = 3

	_ids : Dict[int, int] = {
		755 : 67,
		756 : 67,
		757 : 67
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		755 : [ ( 'oldDiameter', Double ), ( 'newDiameter', Double ), ( 'speed', VarInt ) ],
		756 : [ ( 'oldDiameter', Double ), ( 'newDiameter', Double ), ( 'speed', VarInt ) ],
		757 : [ ( 'oldDiameter', Double ), ( 'newDiameter', Double ), ( 'speed', VarInt ) ]
	}
