"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketSetSlot(Packet):
	__slots__ = ( 'id', 'item', 'windowId', 'slot', 'stateId' )
	
	item : dict
	windowId : int
	slot : int
	stateId : int

	_state : int = 3

	_ids : Dict[int, int] = {
		5 : 47,
		47 : 47,
		76 : 22,
		107 : 22,
		108 : 22,
		109 : 22,
		110 : 22,
		201 : 22,
		210 : 22,
		304 : 22,
		315 : 22,
		321 : 23,
		327 : 23,
		331 : 23,
		335 : 22,
		338 : 22,
		340 : 22,
		351 : 23,
		393 : 23,
		401 : 23,
		402 : 23,
		403 : 23,
		404 : 23,
		477 : 22,
		480 : 22,
		490 : 22,
		498 : 22,
		573 : 23,
		575 : 23,
		578 : 23,
		709 : 23,
		734 : 22,
		735 : 22,
		736 : 22,
		751 : 21,
		755 : 22,
		756 : 22,
		757 : 22,
		1073741839 : 22
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		5 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		47 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		76 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		107 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		108 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		109 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		110 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		201 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		210 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		304 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		315 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		321 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		327 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		331 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		335 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		338 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		340 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		351 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		393 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		401 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		402 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		403 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		404 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		477 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		480 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		490 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		498 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		573 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		575 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		578 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		709 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		734 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		735 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		736 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		751 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		755 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ],
		756 : [ ( 'windowId', Byte ), ( 'stateId', VarInt ), ( 'slot', Short ), ( 'item', Slot ) ],
		757 : [ ( 'windowId', Byte ), ( 'stateId', VarInt ), ( 'slot', Short ), ( 'item', Slot ) ],
		1073741839 : [ ( 'windowId', Byte ), ( 'slot', Short ), ( 'item', Slot ) ]
	}
