"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....definitions import *
from ....types import *

class PacketWindowItems(Packet):
	__slots__ = ( 'id', 'carriedItem', 'items', 'stateId', 'windowId' )
	
	carriedItem : Item
	items : list
	stateId : int
	windowId : int

	def __init__(self, proto:int,
		carriedItem:Item=None,
		items:list=None,
		stateId:int=None,
		windowId:int=None,
		**kwargs
	):
		super().__init__(proto,
			carriedItem=carriedItem,
			items=items,
			stateId=stateId,
			windowId=windowId
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		47 : 48,
		76 : 20,
		107 : 20,
		108 : 20,
		109 : 20,
		110 : 20,
		201 : 20,
		210 : 20,
		304 : 20,
		315 : 20,
		321 : 21,
		327 : 21,
		331 : 21,
		335 : 20,
		338 : 20,
		340 : 20,
		351 : 21,
		393 : 21,
		401 : 21,
		402 : 21,
		403 : 21,
		404 : 21,
		477 : 20,
		480 : 20,
		490 : 20,
		498 : 20,
		573 : 21,
		575 : 21,
		578 : 21,
		709 : 21,
		734 : 20,
		735 : 20,
		736 : 20,
		751 : 19,
		755 : 20,
		756 : 20,
		757 : 20,
		758 : 20,
		759 : 17,
		760 : 17,
		761 : 16
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		76 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		107 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		108 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		109 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		110 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		201 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		210 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		304 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		315 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		321 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		327 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		331 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		335 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		338 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		340 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		351 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		393 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		401 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		402 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		403 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		404 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		477 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		480 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		490 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		498 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		573 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		575 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		578 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		709 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		734 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		735 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		736 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		751 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		755 : [ ( 'windowId', Byte ), ( 'items', ArrayType(Slot, Short, ) ) ],
		756 : [ ( 'windowId', Byte ), ( 'stateId', VarInt ), ( 'items', ArrayType(Slot, VarInt, ) ), ( 'carriedItem', Slot ) ],
		757 : [ ( 'windowId', Byte ), ( 'stateId', VarInt ), ( 'items', ArrayType(Slot, VarInt, ) ), ( 'carriedItem', Slot ) ],
		758 : [ ( 'windowId', Byte ), ( 'stateId', VarInt ), ( 'items', ArrayType(Slot, VarInt, ) ), ( 'carriedItem', Slot ) ],
		759 : [ ( 'windowId', Byte ), ( 'stateId', VarInt ), ( 'items', ArrayType(Slot, VarInt, ) ), ( 'carriedItem', Slot ) ],
		760 : [ ( 'windowId', Byte ), ( 'stateId', VarInt ), ( 'items', ArrayType(Slot, VarInt, ) ), ( 'carriedItem', Slot ) ],
		761 : [ ( 'windowId', Byte ), ( 'stateId', VarInt ), ( 'items', ArrayType(Slot, VarInt, ) ), ( 'carriedItem', Slot ) ]
	}
