"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....definitions import *
from ....types import *

class PacketChatPreview(Packet):
	__slots__ = ( 'id', 'message', 'queryId' )
	
	message : tuple
	queryId : int

	def __init__(self, proto:int,
		message:tuple=None,
		queryId:int=None,
		**kwargs
	):
		super().__init__(proto,
			message=message,
			queryId=queryId
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		759 : 12,
		760 : 12
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		759 : [ ( 'queryId', Int ), ( 'message', OptionalType(String, ) ) ],
		760 : [ ( 'queryId', Int ), ( 'message', OptionalType(String, ) ) ]
	}
