"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketSpawnEntity(Packet):
	__slots__ = ( 'id', 'pitch', 'velocityX', 'type', 'x', 'objectUUID', 'velocityY', 'velocityZ', 'z', 'yaw', 'y', 'entityId', 'entityUUID', 'objectData' )
	
	pitch : int
	velocityX : int
	type : int
	x : Union[int,float]
	objectUUID : str
	velocityY : int
	velocityZ : int
	z : Union[int,float]
	yaw : int
	y : Union[int,float]
	entityId : int
	entityUUID : str
	objectData : Union[dict,int]

	_state : int = 3

	_ids : Dict[int, int] = {
		5 : 14,
		47 : 14,
		76 : 0,
		107 : 0,
		108 : 0,
		109 : 0,
		110 : 0,
		201 : 0,
		210 : 0,
		304 : 0,
		315 : 0,
		321 : 0,
		327 : 0,
		331 : 0,
		335 : 0,
		338 : 0,
		340 : 0,
		351 : 0,
		393 : 0,
		401 : 0,
		402 : 0,
		403 : 0,
		404 : 0,
		477 : 0,
		480 : 0,
		490 : 0,
		498 : 0,
		573 : 0,
		575 : 0,
		578 : 0,
		709 : 0,
		734 : 0,
		735 : 0,
		736 : 0,
		751 : 0,
		755 : 0,
		756 : 0,
		757 : 0,
		1073741839 : 0
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		5 : [ ( 'entityId', VarInt ), ( 'type', Byte ), ( 'x', Int ), ( 'y', Int ), ( 'z', Int ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', StructType(( 'intField', Int ), ( 'velocityX', SwitchType('intField', { 0 : Void }, Short, ) ), ( 'velocityY', SwitchType('intField', { 0 : Void }, Short, ) ), ( 'velocityZ', SwitchType('intField', { 0 : Void }, Short, ) ), ) ) ],
		47 : [ ( 'entityId', VarInt ), ( 'type', Byte ), ( 'x', Int ), ( 'y', Int ), ( 'z', Int ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', StructType(( 'intField', Int ), ( 'velocityX', SwitchType('intField', { 0 : Void }, Short, ) ), ( 'velocityY', SwitchType('intField', { 0 : Void }, Short, ) ), ( 'velocityZ', SwitchType('intField', { 0 : Void }, Short, ) ), ) ) ],
		76 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', Byte ), ( 'x', Int ), ( 'y', Int ), ( 'z', Int ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		107 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		108 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		109 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		110 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		201 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		210 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		304 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		315 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		321 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		327 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		331 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		335 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		338 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		340 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		351 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		393 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		401 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		402 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		403 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		404 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		477 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		480 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		490 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		498 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		573 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		575 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		578 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		709 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		734 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		735 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		736 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		751 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		755 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		756 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		757 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		1073741839 : [ ( 'entityId', VarInt ), ( 'objectUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'pitch', Byte ), ( 'yaw', Byte ), ( 'objectData', Int ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ]
	}
