"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketSpawnEntityLiving(Packet):
	__slots__ = ( 'id', 'pitch', 'headPitch', 'velocityX', 'type', 'x', 'velocityZ', 'z', 'yaw', 'y', 'entityId', 'entityUUID', 'metadata', 'velocityY' )
	
	pitch : int
	headPitch : int
	velocityX : int
	type : int
	x : Union[int,float]
	velocityZ : int
	z : Union[int,float]
	yaw : int
	y : Union[int,float]
	entityId : int
	entityUUID : str
	metadata : bytes
	velocityY : int

	_state : int = 3

	_ids : Dict[int, int] = {
		5 : 15,
		47 : 15,
		76 : 3,
		107 : 3,
		108 : 3,
		109 : 3,
		110 : 3,
		201 : 3,
		210 : 3,
		304 : 3,
		315 : 3,
		321 : 3,
		327 : 3,
		331 : 3,
		335 : 3,
		338 : 3,
		340 : 3,
		351 : 3,
		393 : 3,
		401 : 3,
		402 : 3,
		403 : 3,
		404 : 3,
		477 : 3,
		480 : 3,
		490 : 3,
		498 : 3,
		573 : 3,
		575 : 3,
		578 : 3,
		709 : 3,
		734 : 2,
		735 : 2,
		736 : 2,
		751 : 2,
		755 : 2,
		756 : 2,
		757 : 2,
		1073741839 : 2
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		5 : [ ( 'entityId', VarInt ), ( 'type', Byte ), ( 'x', Int ), ( 'y', Int ), ( 'z', Int ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		47 : [ ( 'entityId', VarInt ), ( 'type', Byte ), ( 'x', Int ), ( 'y', Int ), ( 'z', Int ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		76 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', Byte ), ( 'x', Int ), ( 'y', Int ), ( 'z', Int ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		107 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		108 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		109 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		110 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		201 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		210 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', Byte ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		304 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		315 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		321 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		327 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		331 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		335 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		338 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		340 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		351 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		393 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		401 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		402 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		403 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		404 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		477 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		480 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		490 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		498 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ), ( 'metadata', EntityMetadata ) ],
		573 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		575 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		578 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		709 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		734 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		735 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		736 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		751 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		755 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		756 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		757 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ],
		1073741839 : [ ( 'entityId', VarInt ), ( 'entityUUID', UUID ), ( 'type', VarInt ), ( 'x', Double ), ( 'y', Double ), ( 'z', Double ), ( 'yaw', Byte ), ( 'pitch', Byte ), ( 'headPitch', Byte ), ( 'velocityX', Short ), ( 'velocityY', Short ), ( 'velocityZ', Short ) ]
	}
