"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketScoreboardTeam(Packet):
	__slots__ = ( 'id', 'collisionRule', 'color', 'friendlyFire', 'mode', 'name', 'nameTagVisibility', 'players', 'prefix', 'suffix', 'team' )
	
	collisionRule : bytes
	color : bytes
	friendlyFire : bytes
	mode : int
	name : bytes
	nameTagVisibility : bytes
	players : bytes
	prefix : bytes
	suffix : bytes
	team : str

	def __init__(self, proto:int,
		collisionRule:bytes=None,
		color:bytes=None,
		friendlyFire:bytes=None,
		mode:int=None,
		name:bytes=None,
		nameTagVisibility:bytes=None,
		players:bytes=None,
		prefix:bytes=None,
		suffix:bytes=None,
		team:str=None
	):
		super().__init__(proto,
			collisionRule=collisionRule,
			color=color,
			friendlyFire=friendlyFire,
			mode=mode,
			name=name,
			nameTagVisibility=nameTagVisibility,
			players=players,
			prefix=prefix,
			suffix=suffix,
			team=team
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		47 : 62,
		76 : 64
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'team', String ), ( 'mode', Byte ), ( 'name', SwitchType('mode', { 0 : String, 2 : String }, None, ) ), ( 'prefix', SwitchType('mode', { 0 : String, 2 : String }, None, ) ), ( 'suffix', SwitchType('mode', { 0 : String, 2 : String }, None, ) ), ( 'friendlyFire', SwitchType('mode', { 0 : Byte, 2 : Byte }, None, ) ), ( 'nameTagVisibility', SwitchType('mode', { 0 : String, 2 : String }, None, ) ), ( 'color', SwitchType('mode', { 0 : Byte, 2 : Byte }, None, ) ), ( 'players', SwitchType('mode', { 0 : ArrayType(String, VarInt, ), 3 : ArrayType(String, VarInt, ), 4 : ArrayType(String, VarInt, ) }, None, ) ) ],
		76 : [ ( 'team', String ), ( 'mode', Byte ), ( 'name', SwitchType('mode', { 0 : String, 2 : String }, None, ) ), ( 'prefix', SwitchType('mode', { 0 : String, 2 : String }, None, ) ), ( 'suffix', SwitchType('mode', { 0 : String, 2 : String }, None, ) ), ( 'friendlyFire', SwitchType('mode', { 0 : Byte, 2 : Byte }, None, ) ), ( 'nameTagVisibility', SwitchType('mode', { 0 : String, 2 : String }, None, ) ), ( 'collisionRule', SwitchType('mode', { 0 : String, 2 : String }, None, ) ), ( 'color', SwitchType('mode', { 0 : Byte, 2 : Byte }, None, ) ), ( 'players', SwitchType('mode', { 0 : ArrayType(String, VarInt, ), 3 : ArrayType(String, VarInt, ), 4 : ArrayType(String, VarInt, ) }, None, ) ) ]
	}
