"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....definitions import *
from ....types import *

class PacketChat(Packet):
	__slots__ = ( 'id', 'message', 'position', 'sender' )
	
	message : str
	position : int
	sender : str

	def __init__(self, proto:int,
		message:str=None,
		position:int=None,
		sender:str=None,
		**kwargs
	):
		super().__init__(proto,
			message=message,
			position=position,
			sender=sender
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		47 : 2,
		76 : 15,
		107 : 15,
		108 : 15,
		109 : 15,
		110 : 15,
		201 : 15,
		210 : 15,
		304 : 15,
		315 : 15,
		321 : 16,
		327 : 16,
		331 : 16,
		335 : 15,
		338 : 15,
		340 : 15,
		351 : 14,
		393 : 14,
		401 : 14,
		402 : 14,
		403 : 14,
		404 : 14,
		477 : 14,
		480 : 14,
		490 : 14,
		498 : 14,
		573 : 15,
		575 : 15,
		578 : 15,
		709 : 15,
		734 : 14,
		735 : 14,
		736 : 14,
		751 : 14,
		755 : 15,
		756 : 15,
		757 : 15,
		758 : 15
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'message', String ), ( 'position', Byte ) ],
		76 : [ ( 'message', String ), ( 'position', Byte ) ],
		107 : [ ( 'message', String ), ( 'position', Byte ) ],
		108 : [ ( 'message', String ), ( 'position', Byte ) ],
		109 : [ ( 'message', String ), ( 'position', Byte ) ],
		110 : [ ( 'message', String ), ( 'position', Byte ) ],
		201 : [ ( 'message', String ), ( 'position', Byte ) ],
		210 : [ ( 'message', String ), ( 'position', Byte ) ],
		304 : [ ( 'message', String ), ( 'position', Byte ) ],
		315 : [ ( 'message', String ), ( 'position', Byte ) ],
		321 : [ ( 'message', String ), ( 'position', Byte ) ],
		327 : [ ( 'message', String ), ( 'position', Byte ) ],
		331 : [ ( 'message', String ), ( 'position', Byte ) ],
		335 : [ ( 'message', String ), ( 'position', Byte ) ],
		338 : [ ( 'message', String ), ( 'position', Byte ) ],
		340 : [ ( 'message', String ), ( 'position', Byte ) ],
		351 : [ ( 'message', String ), ( 'position', Byte ) ],
		393 : [ ( 'message', String ), ( 'position', Byte ) ],
		401 : [ ( 'message', String ), ( 'position', Byte ) ],
		402 : [ ( 'message', String ), ( 'position', Byte ) ],
		403 : [ ( 'message', String ), ( 'position', Byte ) ],
		404 : [ ( 'message', String ), ( 'position', Byte ) ],
		477 : [ ( 'message', String ), ( 'position', Byte ) ],
		480 : [ ( 'message', String ), ( 'position', Byte ) ],
		490 : [ ( 'message', String ), ( 'position', Byte ) ],
		498 : [ ( 'message', String ), ( 'position', Byte ) ],
		573 : [ ( 'message', String ), ( 'position', Byte ) ],
		575 : [ ( 'message', String ), ( 'position', Byte ) ],
		578 : [ ( 'message', String ), ( 'position', Byte ) ],
		709 : [ ( 'message', String ), ( 'position', Byte ) ],
		734 : [ ( 'message', String ), ( 'position', Byte ), ( 'sender', UUID ) ],
		735 : [ ( 'message', String ), ( 'position', Byte ), ( 'sender', UUID ) ],
		736 : [ ( 'message', String ), ( 'position', Byte ), ( 'sender', UUID ) ],
		751 : [ ( 'message', String ), ( 'position', Byte ), ( 'sender', UUID ) ],
		755 : [ ( 'message', String ), ( 'position', Byte ), ( 'sender', UUID ) ],
		756 : [ ( 'message', String ), ( 'position', Byte ), ( 'sender', UUID ) ],
		757 : [ ( 'message', String ), ( 'position', Byte ), ( 'sender', UUID ) ],
		758 : [ ( 'message', String ), ( 'position', Byte ), ( 'sender', UUID ) ]
	}
