"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketDestroyEntity(Packet):
	__slots__ = ( 'id', 'entityId' )
	
	entityId : int

	_state : int = 3

	_ids : Dict[int, int] = {
		755 : 58
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		755 : [ ( 'entityId', VarInt ) ]
	}
