"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....types import *

class PacketMapChunkBulk(Packet):
	__slots__ = ( 'id', 'data', 'meta', 'skyLightSent' )
	
	data : bytes
	meta : list
	skyLightSent : bool

	def __init__(self, proto:int,
		data:bytes=None,
		meta:list=None,
		skyLightSent:bool=None,
		**kwargs
	):
		super().__init__(proto,
			data=data,
			meta=meta,
			skyLightSent=skyLightSent
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		47 : 38
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		47 : [ ( 'skyLightSent', Boolean ), ( 'meta', ArrayType(StructType(( 'x', Int ), ( 'z', Int ), ( 'bitMap', UnsignedShort ), ), VarInt, ) ), ( 'data', TrailingData ) ]
	}
