"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union, Optional
from ....packet import Packet
from ....definitions import *
from ....types import *

class PacketChatSuggestions(Packet):
	__slots__ = ( 'id', 'action', 'entries' )
	
	action : int
	entries : list

	def __init__(self, proto:int,
		action:int=None,
		entries:list=None,
		**kwargs
	):
		super().__init__(proto,
			action=action,
			entries=entries
		)

	_state : int = 3

	_ids : Dict[int, int] = {
		760 : 21,
		761 : 20
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		760 : [ ( 'action', VarInt ), ( 'entries', ArrayType(String, VarInt, ) ) ],
		761 : [ ( 'action', VarInt ), ( 'entries', ArrayType(String, VarInt, ) ) ]
	}
