"""[!] This file is autogenerated"""

from typing import Tuple, List, Dict, Union
from ....packet import Packet
from ....types import *

class PacketSculkVibrationSignal(Packet):
	__slots__ = ( 'id', 'sourcePosition', 'destination', 'arrivalTicks', 'destinationIdentifier' )
	
	sourcePosition : tuple
	destination : bytes
	arrivalTicks : int
	destinationIdentifier : str

	_state : int = 3

	_ids : Dict[int, int] = {
		755 : 5,
		756 : 5,
		757 : 5,
		1073741839 : 5
	}
	_definitions : Dict[int, List[Tuple[str, Type]]] = {
		755 : [ ( 'sourcePosition', Position ), ( 'destinationIdentifier', String ), ( 'destination', SwitchType('destinationIdentifier', { 'block' : Position, 'entityId' : VarInt }, None, ) ), ( 'arrivalTicks', VarInt ) ],
		756 : [ ( 'sourcePosition', Position ), ( 'destinationIdentifier', String ), ( 'destination', SwitchType('destinationIdentifier', { 'block' : Position, 'entityId' : VarInt }, None, ) ), ( 'arrivalTicks', VarInt ) ],
		757 : [ ( 'sourcePosition', Position ), ( 'destinationIdentifier', String ), ( 'destination', SwitchType('destinationIdentifier', { 'block' : Position, 'entityId' : VarInt }, None, ) ), ( 'arrivalTicks', VarInt ) ],
		1073741839 : [ ( 'sourcePosition', Position ), ( 'destinationIdentifier', String ), ( 'destination', SwitchType('destinationIdentifier', { 'block' : Position, 'entityId' : VarInt }, None, ) ), ( 'arrivalTicks', VarInt ) ]
	}
